### ISSUE TITLE
Not working with xregexp 3.1.0 anymore

### ISSUE THREAD

**Issue by nerk** [jiahansu/BridJS#2]
Bridjs specifies version of XRegExp as

```
"xregexp": ">=2.0.0"
```
which will use the latest XRegExp, currently  3.1.0. As of 3.1.0, 
```
require('xregexp').XRegExp
```
is no longer supported and Bridjs fails:
```
C:\Users\thomas.kern\work\webstorm\demonstrator\node_modules\gazejs\node_modules\bridjs\lib\abstract_struct.js:43
        arrayExp = XRegExp("(?<type>\\w+)\\[(?<count>\\d)\\]");
                   ^

TypeError: XRegExp is not a function
    at Object.<anonymous> 
```

XRegExp 3.0.0 still works.

**Comment by jiahansu** [comment]
It has been fixed in 0.3.4-5

Thanks for you report this issue
